### ISSUE TITLE
package daget for pip

### ISSUE THREAD

**Issue by borsna** [borsna/daget#12]
Resructure repo and add support for distribution and installation via pip.

**Comment by aliirz** [comment]
@borsna  I am working on this

**Comment by aliirz** [comment]
Check PR#15

**Comment by borsna** [comment]
building localy works but seems like pipy requires api upload so twine did not work for me unfortunatly.
Have tried to get build and upload via github actions to work but it seems to fail when trying to get the built package from the `dirst/` directory.

Tried the guide from https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/ 
(tried several other setups but it seems to fail to find anything in the dist-directory)
https://github.com/borsna/daget/actions/runs/6189246049/job/16802942577

Will have to figure out the proper way to do the build in a github pipeline to get this to work.
Have you done any similar things using github actions @aliirz?

**Comment by borsna** [comment]
Thankful for your help :smiley: 
Got tired of testing and failing for an hour.
I guess there is a simple error but i can´t quite figure out whats not working during the build (not quite sure the dist-files is realy created or not in the github env) -> publish process

**Comment by borsna** [comment]
got it to work via `twine` using a token instead by going by this guide:
https://kynan.github.io/blog/2020/05/23/how-to-upload-your-package-to-the-python-package-index-pypi-test-server

Was missing the long_description in the `0.1` release so i did a new release for the first draft:
https://pypi.org/project/daget/

Would be nice to get the github action working but this method will also work.
Thanks for the help pointing me in the right direction :+1:

**Comment by aliirz** [comment]
glad you got it to work.
